<a href="https://colab.research.google.com/github/cindyshin2211/Website_Fingerprinting_MLB/blob/%EC%8B%A0%EC%84%B1%ED%98%84/DecisionTree_RandomForest(mon_unmon).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Exploration

In [1]:
import pandas as pd
import numpy as np

In [11]:
mon=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/EWHA_machine_ learning/mon.csv")
monunmon=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/EWHA_machine_ learning/monunmon.csv")

In [12]:
monunmon.head()

Total Packets  Incoming Packets  Outgoing Packets  Incoming Ratio  \
0         1421.0             121.0            1300.0        0.085151   
1          518.0              80.0             438.0        0.154440   
2         1358.0             118.0            1240.0        0.086892   
3         1446.0             122.0            1324.0        0.084371   
4         1406.0             115.0            1291.0        0.081792   

   Outgoing Ratio  Outgoing Std  Outgoing Mean  Packets per Second  \
0        0.914849    515.483953     773.322314          140.138067   
1        0.845560    139.231951     226.162500           50.984252   
2        0.913108    472.735508     786.110169          122.232223   
3        0.915629    513.916038     820.139344          108.233533   
4        0.918208    503.993490     789.608696          132.142857   

   First 30 Incoming  First 30 Outgoing  Inter-arrival Mean  \
0                9.0               21.0            0.007141   
1                8.0               22.0            0.019652   
2                7.0               23.0            0.008187   
3                9.0               21.0            0.009246   
4                8.0               22.0            0.007573   

   Inter-arrival Std  Concentration Mean  Concentration Std  Alternative Sum  \
0           0.041168            1.680556           2.510126        -603648.0   
1           0.163930            3.076923           3.011811        -183296.0   
2           0.066661            1.735294           2.361565        -574464.0   
3           0.047809            1.671233           2.183718        -615424.0   
4           0.038760            1.619718           2.112113        -602112.0   

   Label  
0      0  
1      0  
2      0  
3      0  
4      0

In [5]:
mon.head()

Total Packets  Incoming Packets  Outgoing Packets  Incoming Ratio  \
0         1421.0             121.0            1300.0        0.085151   
1          518.0              80.0             438.0        0.154440   
2         1358.0             118.0            1240.0        0.086892   
3         1446.0             122.0            1324.0        0.084371   
4         1406.0             115.0            1291.0        0.081792   

   Outgoing Ratio  Outgoing Std  Outgoing Mean  Packets per Second  \
0        0.914849    515.483953     773.322314          140.138067   
1        0.845560    139.231951     226.162500           50.984252   
2        0.913108    472.735508     786.110169          122.232223   
3        0.915629    513.916038     820.139344          108.233533   
4        0.918208    503.993490     789.608696          132.142857   

   First 30 Incoming  First 30 Outgoing  Inter-arrival Mean  \
0                9.0               21.0            0.007141   
1                8.0               22.0            0.019652   
2                7.0               23.0            0.008187   
3                9.0               21.0            0.009246   
4                8.0               22.0            0.007573   

   Inter-arrival Std  Concentration Mean  Concentration Std  Alternative Sum  \
0           0.041168            1.680556           2.510126        -603648.0   
1           0.163930            3.076923           3.011811        -183296.0   
2           0.066661            1.735294           2.361565        -574464.0   
3           0.047809            1.671233           2.183718        -615424.0   
4           0.038760            1.619718           2.112113        -602112.0   

   Label  
0      0  
1      0  
2      0  
3      0  
4      0

In [13]:
monunmon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Total Packets       22000 non-null  float64
 1   Incoming Packets    22000 non-null  float64
 2   Outgoing Packets    22000 non-null  float64
 3   Incoming Ratio      22000 non-null  float64
 4   Outgoing Ratio      22000 non-null  float64
 5   Outgoing Std        22000 non-null  float64
 6   Outgoing Mean       22000 non-null  float64
 7   Packets per Second  22000 non-null  float64
 8   First 30 Incoming   22000 non-null  float64
 9   First 30 Outgoing   22000 non-null  float64
 10  Inter-arrival Mean  22000 non-null  float64
 11  Inter-arrival Std   22000 non-null  float64
 12  Concentration Mean  22000 non-null  float64
 13  Concentration Std   22000 non-null  float64
 14  Alternative Sum     22000 non-null  float64
 15  Label               22000 non-null  int64  
dtypes: f

In [7]:
mon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19000 entries, 0 to 18999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Total Packets       19000 non-null  float64
 1   Incoming Packets    19000 non-null  float64
 2   Outgoing Packets    19000 non-null  float64
 3   Incoming Ratio      19000 non-null  float64
 4   Outgoing Ratio      19000 non-null  float64
 5   Outgoing Std        19000 non-null  float64
 6   Outgoing Mean       19000 non-null  float64
 7   Packets per Second  19000 non-null  float64
 8   First 30 Incoming   19000 non-null  float64
 9   First 30 Outgoing   19000 non-null  float64
 10  Inter-arrival Mean  19000 non-null  float64
 11  Inter-arrival Std   19000 non-null  float64
 12  Concentration Mean  19000 non-null  float64
 13  Concentration Std   19000 non-null  float64
 14  Alternative Sum     19000 non-null  float64
 15  Label               19000 non-null  int64  
dtypes: f

In [14]:
monunmon.Label.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, -1])

In [16]:
data=monunmon.copy()

In [24]:
data.loc[data.Label != -1, "Label"] = 1

In [25]:
data.Label.unique()

array([ 1, -1])

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Total Packets       22000 non-null  float64
 1   Incoming Packets    22000 non-null  float64
 2   Outgoing Packets    22000 non-null  float64
 3   Incoming Ratio      22000 non-null  float64
 4   Outgoing Ratio      22000 non-null  float64
 5   Outgoing Std        22000 non-null  float64
 6   Outgoing Mean       22000 non-null  float64
 7   Packets per Second  22000 non-null  float64
 8   First 30 Incoming   22000 non-null  float64
 9   First 30 Outgoing   22000 non-null  float64
 10  Inter-arrival Mean  22000 non-null  float64
 11  Inter-arrival Std   22000 non-null  float64
 12  Concentration Mean  22000 non-null  float64
 13  Concentration Std   22000 non-null  float64
 14  Alternative Sum     22000 non-null  float64
 15  Label               22000 non-null  int64  
dtypes: f

# Using Desision Tree

In [28]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import f1_score

# 특성과 라벨 분리
X = data.drop(columns=['Label'])
y = data['Label']

# 학습용 데이터와 테스트용 데이터 분할 (80% 학습, 20% 테스트)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Decision Tree 모델 생성 및 학습
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# 예측 수행
y_pred = model.predict(X_test)

# 모델 평가
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='binary')  # 이진 분류(binary)
print("Accuracy:", accuracy)
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("F1 Score:", f1)

Accuracy: 0.8679545454545454
Classification Report:
               precision    recall  f1-score   support

          -1       0.51      0.53      0.52       590
           1       0.93      0.92      0.92      3810

    accuracy                           0.87      4400
   macro avg       0.72      0.72      0.72      4400
weighted avg       0.87      0.87      0.87      4400

Confusion Matrix:
 [[ 312  278]
 [ 303 3507]]
F1 Score: 0.9235023041474655


# Using Random Forest

In [29]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

# 특성과 라벨 분리
X = data.drop(columns=['Label'])
y = data['Label']

# 학습용 데이터와 테스트용 데이터 분할 (80% 학습, 20% 테스트)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Random Forest 모델 생성 및 학습
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# 예측 수행
y_pred = model.predict(X_test)

# 모델 평가
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='binary')  # 이진 분류(binary)
print("Accuracy:", accuracy)
print("F1 Score:", f1)
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 0.9115909090909091
F1 Score: 0.9508155266152485
Classification Report:
               precision    recall  f1-score   support

          -1       0.83      0.43      0.56       590
           1       0.92      0.99      0.95      3810

    accuracy                           0.91      4400
   macro avg       0.88      0.71      0.76      4400
weighted avg       0.91      0.91      0.90      4400

Confusion Matrix:
 [[ 251  339]
 [  50 3760]]
